package Model;

import java.util.ArrayList;

/**
 * A descriptor of a model generated by any methods
 * E.g, a dependency model generated by WEKA.
 * This is an ideal model for prototype.
 * In real world, the model will not be this simple.
 * @author szhang
 */

public class ModelDescriptor {
	
	public String missingAttribute;
	public ArrayList<String> sourceAttributes;
	public String sampledFileName;
	public Function function;
	
	public ModelDescriptor(){
		
	}
	
	public ModelDescriptor(String missingAttribute,
			ArrayList<String> sourceAttributes, String sampledFileName,
			Function function) {
		super();
		this.missingAttribute = missingAttribute;
		this.sourceAttributes = sourceAttributes;
		this.sampledFileName = sampledFileName;
		this.function = function;
	}
	
	
}
